insert into poll (poll_id, question) values (1, 'What is your favorite color?');
    insert into option (option_id, option_value, poll_id) values (1, 'Red', 1);
    insert into option (option_id, option_value, poll_id) values (2, 'Blue', 1);
    insert into option (option_id, option_value, poll_id) values (3, 'White', 1);

insert into poll (poll_id, question) values (2, 'What is your favorite color?');
    insert into option (option_id, option_value, poll_id) values (4, 'Red', 2);
    insert into option (option_id, option_value, poll_id) values (5, 'Green', 2);
    insert into option (option_id, option_value, poll_id) values (6, 'Purple', 2);
insert into poll (poll_id, question) values (3, 'What is your favorite color?');
    insert into option (option_id, option_value, poll_id) values (7, 'Red', 3);
    insert into option (option_id, option_value, poll_id) values (8, 'Green', 3);
    insert into option (option_id, option_value, poll_id) values (9, 'Purple', 3);
insert into poll (poll_id, question) values (4, 'What is your favorite color?');
    insert into option (option_id, option_value, poll_id) values (10, 'Gold', 4);
    insert into option (option_id, option_value, poll_id) values (11, 'Blue', 4);
    insert into option (option_id, option_value, poll_id) values (12, 'Black', 4);
insert into poll (poll_id, question) values (5, 'What is your favorite color?');
    insert into option (option_id, option_value, poll_id) values (13, 'Red', 5);
    insert into option (option_id, option_value, poll_id) values (14, 'Blue', 5);
    insert into option (option_id, option_value, poll_id) values (15, 'White', 5);
insert into poll (poll_id, question) values (6, 'What is your favorite color?');
    insert into option (option_id, option_value, poll_id) values (16, 'Red', 6);
    insert into option (option_id, option_value, poll_id) values (17, 'Blue', 6);
    insert into option (option_id, option_value, poll_id) values (18, 'White', 6);
insert into poll (poll_id, question) values (7, 'What is your favorite color?');
    insert into option (option_id, option_value, poll_id) values (19, 'Red', 7);
    insert into option (option_id, option_value, poll_id) values (20, 'Green', 7);
    insert into option (option_id, option_value, poll_id) values (21, 'Purple', 7);
insert into poll (poll_id, question) values (8, 'What is your favorite color?');
    insert into option (option_id, option_value, poll_id) values (22, 'Red', 8);
    insert into option (option_id, option_value, poll_id) values (23, 'Green', 8);
    insert into option (option_id, option_value, poll_id) values (24, 'Purple', 8);
insert into poll (poll_id, question) values (9, 'What is your favorite color?');
    insert into option (option_id, option_value, poll_id) values (25, 'Gold', 9);
    insert into option (option_id, option_value, poll_id) values (26, 'Blue', 9);
    insert into option (option_id, option_value, poll_id) values (27, 'Black', 9);
insert into poll (poll_id, question) values (10, 'What is your favorite color?');
    insert into option (option_id, option_value, poll_id) values (28, 'Red', 10);
    insert into option (option_id, option_value, poll_id) values (29, 'Blue', 10);
    insert into option (option_id, option_value, poll_id) values (30, 'White', 10);
    insert into poll (poll_id, question) values (11, 'What is your favorite color?');
    insert into option (option_id, option_value, poll_id) values (31, 'Red', 11);
    insert into option (option_id, option_value, poll_id) values (32, 'Blue', 11);
    insert into option (option_id, option_value, poll_id) values (33, 'White', 11);
insert into poll (poll_id, question) values (12, 'What is your favorite color?');
    insert into option (option_id, option_value, poll_id) values (34, 'Red', 12);
    insert into option (option_id, option_value, poll_id) values (35, 'Green', 12);
    insert into option (option_id, option_value, poll_id) values (36, 'Purple', 12);
insert into poll (poll_id, question) values (13, 'What is your favorite color?');
    insert into option (option_id, option_value, poll_id) values (37, 'Red', 13);
    insert into option (option_id, option_value, poll_id) values (38, 'Green', 13);
    insert into option (option_id, option_value, poll_id) values (39, 'Purple', 13);
insert into poll (poll_id, question) values (14, 'What is your favorite color?');
    insert into option (option_id, option_value, poll_id) values (40, 'Gold', 14);
    insert into option (option_id, option_value, poll_id) values (41, 'Blue', 14);
    insert into option (option_id, option_value, poll_id) values (42, 'Black', 14);
insert into poll (poll_id, question) values (15, 'What is your favorite color?');
    insert into option (option_id, option_value, poll_id) values (43, 'Red', 15);
    insert into option (option_id, option_value, poll_id) values (44, 'Blue', 15);
    insert into option (option_id, option_value, poll_id) values (45, 'White', 15);