insert into poll (poll_id, question) values (1, 'What is your favorite color?');
    insert into option (option_id, option_value, poll_id) values (1, 'Red', 1);
    insert into option (option_id, option_value, poll_id) values (2, 'Blue', 1);
    insert into option (option_id, option_value, poll_id) values (3, 'White', 1);
insert into poll (poll_id, question) values (1, 'What is your favorite color?');
    insert into option (option_id, option_value, poll_id) values (1, 'Red', 1);
    insert into option (option_id, option_value, poll_id) values (2, 'Green', 1);
    insert into option (option_id, option_value, poll_id) values (3, 'Purple', 1);
insert into poll (poll_id, question) values (1, 'What is your favorite color?');
    insert into option (option_id, option_value, poll_id) values (1, 'Red', 1);
    insert into option (option_id, option_value, poll_id) values (2, 'Green', 1);
    insert into option (option_id, option_value, poll_id) values (3, 'Purple', 1);
insert into poll (poll_id, question) values (1, 'What is your favorite color?');
    insert into option (option_id, option_value, poll_id) values (1, 'Gold', 1);
    insert into option (option_id, option_value, poll_id) values (2, 'Blue', 1);
    insert into option (option_id, option_value, poll_id) values (3, 'Black', 1);
insert into poll (poll_id, question) values (1, 'What is your favorite color?');
    insert into option (option_id, option_value, poll_id) values (1, 'Red', 1);
    insert into option (option_id, option_value, poll_id) values (2, 'Blue', 1);
    insert into option (option_id, option_value, poll_id) values (3, 'White', 1);
    insert into poll (poll_id, question) values (1, 'What is your favorite color?');
    insert into option (option_id, option_value, poll_id) values (1, 'Red', 1);
    insert into option (option_id, option_value, poll_id) values (2, 'Blue', 1);
    insert into option (option_id, option_value, poll_id) values (3, 'White', 1);
insert into poll (poll_id, question) values (1, 'What is your favorite color?');
    insert into option (option_id, option_value, poll_id) values (1, 'Red', 1);
    insert into option (option_id, option_value, poll_id) values (2, 'Green', 1);
    insert into option (option_id, option_value, poll_id) values (3, 'Purple', 1);
insert into poll (poll_id, question) values (1, 'What is your favorite color?');
    insert into option (option_id, option_value, poll_id) values (1, 'Red', 1);
    insert into option (option_id, option_value, poll_id) values (2, 'Green', 1);
    insert into option (option_id, option_value, poll_id) values (3, 'Purple', 1);
insert into poll (poll_id, question) values (1, 'What is your favorite color?');
    insert into option (option_id, option_value, poll_id) values (1, 'Gold', 1);
    insert into option (option_id, option_value, poll_id) values (2, 'Blue', 1);
    insert into option (option_id, option_value, poll_id) values (3, 'Black', 1);
insert into poll (poll_id, question) values (1, 'What is your favorite color?');
    insert into option (option_id, option_value, poll_id) values (1, 'Red', 1);
    insert into option (option_id, option_value, poll_id) values (2, 'Blue', 1);
    insert into option (option_id, option_value, poll_id) values (3, 'White', 1);
    insert into poll (poll_id, question) values (1, 'What is your favorite color?');
    insert into option (option_id, option_value, poll_id) values (1, 'Red', 1);
    insert into option (option_id, option_value, poll_id) values (2, 'Blue', 1);
    insert into option (option_id, option_value, poll_id) values (3, 'White', 1);
insert into poll (poll_id, question) values (1, 'What is your favorite color?');
    insert into option (option_id, option_value, poll_id) values (1, 'Red', 1);
    insert into option (option_id, option_value, poll_id) values (2, 'Green', 1);
    insert into option (option_id, option_value, poll_id) values (3, 'Purple', 1);
insert into poll (poll_id, question) values (1, 'What is your favorite color?');
    insert into option (option_id, option_value, poll_id) values (1, 'Red', 1);
    insert into option (option_id, option_value, poll_id) values (2, 'Green', 1);
    insert into option (option_id, option_value, poll_id) values (3, 'Purple', 1);
insert into poll (poll_id, question) values (1, 'What is your favorite color?');
    insert into option (option_id, option_value, poll_id) values (1, 'Gold', 1);
    insert into option (option_id, option_value, poll_id) values (2, 'Blue', 1);
    insert into option (option_id, option_value, poll_id) values (3, 'Black', 1);
insert into poll (poll_id, question) values (1, 'What is your favorite color?');
    insert into option (option_id, option_value, poll_id) values (1, 'Red', 1);
    insert into option (option_id, option_value, poll_id) values (2, 'Blue', 1);
    insert into option (option_id, option_value, poll_id) values (3, 'White', 1);